// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQLHPfUJ6ucdPb0ak4YG-AeEkqrJnDbk',
    appId: '1:409648398649:web:15395b46acd401cc7f28e8',
    messagingSenderId: '409648398649',
    projectId: 'autenticacion-firebase-10b',
    authDomain: 'autenticacion-firebase-10b.firebaseapp.com',
    storageBucket: 'autenticacion-firebase-10b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5_YlUZGKp-JYA4MLHbTUPuHQbGA0Hgs',
    appId: '1:409648398649:android:21de7ec0eecfaf937f28e8',
    messagingSenderId: '409648398649',
    projectId: 'autenticacion-firebase-10b',
    storageBucket: 'autenticacion-firebase-10b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0zdvb_B7kt9eigCDpoI4MESwP5MkS1mY',
    appId: '1:409648398649:ios:e3852ca94adda7a17f28e8',
    messagingSenderId: '409648398649',
    projectId: 'autenticacion-firebase-10b',
    storageBucket: 'autenticacion-firebase-10b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCldMsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0zdvb_B7kt9eigCDpoI4MESwP5MkS1mY',
    appId: '1:409648398649:ios:e3852ca94adda7a17f28e8',
    messagingSenderId: '409648398649',
    projectId: 'autenticacion-firebase-10b',
    storageBucket: 'autenticacion-firebase-10b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCldMsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQLHPfUJ6ucdPb0ak4YG-AeEkqrJnDbk',
    appId: '1:409648398649:web:59f344c42f21ff2f7f28e8',
    messagingSenderId: '409648398649',
    projectId: 'autenticacion-firebase-10b',
    authDomain: 'autenticacion-firebase-10b.firebaseapp.com',
    storageBucket: 'autenticacion-firebase-10b.firebasestorage.app',
  );
}
